# Generated by Django 4.2.1 on 2023-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완료')], default='', max_length=5, verbose_name='질문 상태'),
            preserve_default=False,
        ),
    ]
